services:
  web:
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "3003:4000"
    volumes:
      - .:/srv/app
      - bundle-cache:/bundle
      - rails-data:/srv/app/data
      - rails-log:/srv/app/log
    models:
      - llm

models:
  llm:
    model: ai/gemma3

volumes:
  bundle-cache:
    driver: local
  rails-data:
    driver: local
  rails-log:
    driver: local
  rails-tmp:
    driver: local
